version: "3.4"

services:
  go-chat-manager-node-dev:
    build:
      context: .
      target: node-dev
    image: alexstojda/go-chat-manager-node-dev:${VERSION:-local}

  go-chat-manager-go-dev:
    build:
      context: .
      target: go-dev
    image: alexstojda/go-chat-manager-go-dev:${VERSION:-local}

  go-chat-manager:
    build: .
    image: alexstojda/go-chat-manager:${VERSION:-local}
    environment:
      - SPA_PATH=/app/build
    ports:
      - "8080"